os: osx
osx_image: xcode10.1
language: objective-c
script: xcodebuild -workspace KVConstraintKit.xcworkspace -scheme KVConstraintKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

# whitelist
branches:
only:
- swift_4.2
