os: osx
osx_image: xcode10.1
language: swift
script:
    - xcodebuild -workspace KVConstraintKit.xcworkspace -scheme KVConstraintKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xcodebuild -workspace KVConstraintKit.xcworkspace -scheme KVConstraintKit-macOS -sdk macosx ONLY_ACTIVE_ARCH=NO
    - xcodebuild -workspace KVConstraintKit.xcworkspace -scheme KVConstraintKit-tvOS -sdk appletvos ONLY_ACTIVE_ARCH=NO

# whitelist
branches:
only:
- swift_4.2
